"use client";

import { useEffect, useState } from "react";
import { analyzeEmail, listCases, clearCases, AnalysisResult, CaseSummary } from "@/lib/api";
import { SAMPLE_EMAIL } from "@/lib/sample";
import VerdictStamp from "@/components/VerdictStamp";
import NBCard from "@/components/NBCard";
import RelayPath from "@/components/RelayPath";
import { HeaderTable, IndicatorList, GeoCard, SPFCard, CaseLog } from "@/components/DetailBlocks";

export default function Home() {
  const [rawEmail, setRawEmail] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [cases, setCases] = useState<CaseSummary[]>([]);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    listCases().then(setCases).catch(() => {});
  }, []);

  async function handleAnalyze() {
    if (!rawEmail.trim()) {
      alert("Paste an email or load the sample case first.");
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const data = await analyzeEmail(rawEmail);
      setResult(data);
      const updated = await listCases();
      setCases(updated);
    } catch (e: any) {
      setError(e.message || "Analysis failed — is the backend running and NEXT_PUBLIC_API_URL set correctly?");
    } finally {
      setLoading(false);
    }
  }

  async function handleClearHistory() {
    await clearCases();
    setCases([]);
  }

  function downloadReport() {
    if (!result) return;
    const lines: string[] = [];
    lines.push("=".repeat(60));
    lines.push("FORENSIC ANALYSIS REPORT — CASE " + result.case_id);
    lines.push("Problem Statement 26106 — AI-Powered Email Threat Detection,");
    lines.push("GeoLocation and Forensic Intelligence Platform");
    lines.push("Organization: AICTE — Cyber Security Cell");
    lines.push("Generated: " + result.generated_at);
    lines.push("=".repeat(60));
    lines.push("");
    lines.push(`VERDICT: ${result.verdict}   |   RISK SCORE: ${result.score}/100`);
    lines.push(`AI TEXT CLASSIFIER: ${Math.round(result.nb_classifier.probability_phishing * 100)}% estimated probability of phishing (${result.nb_classifier.model})`);
    lines.push("");
    lines.push("-- Header Summary --");
    lines.push("Subject      : " + (result.headers.subject || "—"));
    lines.push("From         : " + (result.headers.from || "—"));
    lines.push("Reply-To     : " + (result.headers.reply_to || "— (not set)"));
    lines.push("Return-Path  : " + (result.headers.return_path || "—"));
    lines.push("Authentication: " + (result.headers.auth_results || "— (none present)"));
    lines.push("");
    lines.push(`-- Indicators (${result.indicators.length}) --`);
    result.indicators.forEach((i, n) => lines.push(`${n + 1}. [${i.sev.toUpperCase()}] ${i.text}`));
    lines.push("");
    lines.push("-- Live SPF Check (DNS-over-HTTPS, independent of header) --");
    if (result.spf_live?.found === true) {
      lines.push("SPF record found. Origin IP mechanism match: " + (result.spf_live.mechanism_match ? "YES" : "NO"));
    } else if (result.spf_live?.found === false) {
      lines.push("No SPF record published for sender domain.");
    } else {
      lines.push("SPF live check not performed or unavailable.");
    }
    lines.push("");
    lines.push("-- Relay Path (origin to recipient) --");
    result.relay_hops.forEach((h, i) => lines.push(`${i + 1}. ${h.host}${h.ip ? " [" + h.ip + "]" : ""} (${h.is_private ? "internal" : "public"})`));
    lines.push("");
    lines.push("-- Origin GeoLocation --");
    if (result.geolocation) {
      lines.push(`Location: ${result.geolocation.city}, ${result.geolocation.region}, ${result.geolocation.country}`);
      lines.push(`Network : ${result.geolocation.isp}`);
      lines.push(`Source  : ${result.geolocation.simulated ? "Offline reference dataset" : "Live ipapi.co lookup"}`);
    } else {
      lines.push("No resolvable public IP found in header chain.");
    }
    lines.push("");
    lines.push("=".repeat(60));
    lines.push("Generated by an automated prototype for hackathon demonstration");
    lines.push("purposes; not a substitute for certified digital forensic procedure.");

    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `${result.case_id}_forensic_report.txt`;
    a.click();
  }

  return (
    <div className="max-w-[1100px] mx-auto">
      <div className="flex gap-1.5 pl-6">
        <div className="bg-card border border-ink/20 border-b-0 rounded-t-lg px-4 pt-2 pb-2.5 font-mono text-[11px] tracking-wider uppercase font-semibold">
          Case 26106
        </div>
        <div className="bg-paperdark border border-ink/20 border-b-0 rounded-t-lg px-4 pt-2 pb-2.5 font-mono text-[11px] tracking-wider uppercase text-inksoft">
          Cyber Security Cell · AICTE
        </div>
      </div>

      <div className="bg-card border border-ink/20 rounded-b-lg rounded-tr-lg shadow-xl px-7 pt-7 pb-6">
        <header className="flex justify-between items-start border-b-2 border-ink pb-4 mb-5 gap-5 flex-wrap">
          <div>
            <h1 className="stamp-text text-2xl mb-1">Email Threat &amp; Forensic Intelligence — Intake</h1>
            <p className="text-[13px] text-inksoft m-0">
              AI-Powered Email Threat Detection, GeoLocation &amp; Forensic Intelligence Platform
            </p>
          </div>
          <div className="text-right font-mono text-[11px] text-inksoft leading-relaxed">
            CASE ID: <b className="text-ink">{result?.case_id || "—"}</b>
            <br />
            STATUS:{" "}
            <b className="text-ink">
              {loading ? "ANALYSIS IN PROGRESS" : result ? `ANALYSIS COMPLETE — ${result.verdict}` : "AWAITING EVIDENCE"}
            </b>
          </div>
        </header>

        <div className="grid md:grid-cols-2 gap-6">
          <div>
            <label className="font-mono text-[10.5px] uppercase tracking-wider text-inksoft block mb-1.5">
              Evidence — raw email source (headers + body)
            </label>
            <textarea
              className="w-full min-h-[220px] bg-[#fffdf7] border border-ink/20 rounded-md p-3 font-mono text-xs leading-relaxed resize-y"
              spellCheck={false}
              value={rawEmail}
              onChange={(e) => setRawEmail(e.target.value)}
              placeholder="Paste full raw email source here (including headers: From, Reply-To, Return-Path, Received, Authentication-Results)…"
            />
            <div className="flex gap-2.5 mt-3 flex-wrap">
              <button
                onClick={handleAnalyze}
                disabled={loading}
                className="font-mono text-[11.5px] uppercase tracking-wide px-4 py-2.5 rounded-md border border-ink bg-ink text-card disabled:opacity-50"
              >
                {loading ? "Analyzing…" : "Analyze Evidence"}
              </button>
              <button
                onClick={() => setRawEmail(SAMPLE_EMAIL)}
                className="font-mono text-[11.5px] uppercase tracking-wide px-4 py-2.5 rounded-md border border-ink"
              >
                Load Sample Case
              </button>
              <button
                onClick={() => {
                  setRawEmail("");
                  setResult(null);
                }}
                className="font-mono text-[11.5px] uppercase tracking-wide px-4 py-2.5 rounded-md border border-ink"
              >
                Clear
              </button>
            </div>
            {error && <p className="text-alert text-sm mt-2 font-mono">{error}</p>}
          </div>

          <VerdictStamp verdict={result?.verdict ?? null} score={result?.score ?? null} />
        </div>

        {result && (
          <div>
            <SectionTitle>Header Forensics</SectionTitle>
            <HeaderTable headers={result.headers} />

            <SectionTitle>AI Classifier — Naive Bayes Phishing Model</SectionTitle>
            <NBCard nb={result.nb_classifier} />

            <SectionTitle>Relay Path (Received Chain)</SectionTitle>
            <RelayPath hops={result.relay_hops} />

            <SectionTitle>Content &amp; Link Heuristics</SectionTitle>
            <IndicatorList indicators={result.indicators} />

            <SectionTitle>GeoLocation &amp; Live SPF — Origin IP</SectionTitle>
            <GeoCard geo={result.geolocation} targetIp={result.target_ip} />
            <SPFCard spf={result.spf_live} domain={result.headers.from?.match(/@([\w.\-]+)/)?.[1] || null} />

            <SectionTitle>
              Case Log <span className="normal-case font-sans font-normal">(persisted server-side, shared across analysts)</span>
            </SectionTitle>
            <CaseLog cases={cases} />
            <div className="mt-3">
              <button
                onClick={handleClearHistory}
                className="font-mono text-[11.5px] uppercase tracking-wide px-4 py-2.5 rounded-md border border-ink"
              >
                Clear Case History
              </button>
            </div>

            <SectionTitle>Forensic Report</SectionTitle>
            <div className="flex gap-2.5 mt-2">
              <button
                onClick={downloadReport}
                className="font-mono text-[11.5px] uppercase tracking-wide px-4 py-2.5 rounded-md border border-ink bg-ink text-card"
              >
                Download Forensic Report (.txt)
              </button>
            </div>
          </div>
        )}
      </div>
      <footer className="text-center font-mono text-[10.5px] text-inksoft mt-5 tracking-wide">
        PROTOTYPE — Problem Statement 26106 · For hackathon demonstration only · Not for operational use
      </footer>
    </div>
  );
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <div className="font-mono text-[11px] tracking-wider uppercase border-b border-ink/20 pb-1.5 mt-6 mb-3">
      {children}
    </div>
  );
}
